#!/bin/bash
# =============================================================
# vm-resize-agent - Generic Pipeline Wrapper
# =============================================================
# DO NOT edit this file.
# Add your pipeline steps to steps.conf instead.
# =============================================================

CONF="$(dirname "$0")/steps.conf"
EMIT="$(dirname "$0")/../agent/emit_event.py"
START_TIME=$(date +%s)

# validate config exists
if [ ! -f "$CONF" ]; then
    echo "[ERROR] steps.conf not found at $CONF"
    exit 1
fi

# count total steps (skip comments + empty lines)
STEPS_TOTAL=$(grep -v '^#' "$CONF" | grep -v '^[[:space:]]*$' | wc -l)

if [ "$STEPS_TOTAL" -eq 0 ]; then
    echo "[ERROR] No steps found in steps.conf"
    exit 1
fi

STEPS_DONE=0

echo "================================================"
echo " vm-resize-agent pipeline starting"
echo " Total steps: $STEPS_TOTAL"
echo " Started at:  $(date)"
echo "================================================"

# failure handler
fail() {
    END_TIME=$(date +%s)
    DURATION=$(( END_TIME - START_TIME ))
    echo ""
    echo "[FAILED] Step $STEPS_DONE/$STEPS_TOTAL failed: $1"
    echo "[FAILED] Duration so far: ${DURATION}s"
    echo "[FAILED] Sending failure alert..."
    python3 "$EMIT" FAILURE "$STEPS_DONE" "$STEPS_TOTAL" "$DURATION" "$1"
    exit 1
}

# run each step from steps.conf
while IFS= read -r step; do

    # skip comments and empty lines
    [[ "$step" =~ ^[[:space:]]*#.*$ ]] && continue
    [[ -z "${step// }" ]] && continue

    STEPS_DONE=$((STEPS_DONE + 1))
    echo ""
    echo "[$STEPS_DONE/$STEPS_TOTAL] $(date +%H:%M:%S) Running: $step"

    eval "$step"
    EXIT_CODE=$?

    if [ $EXIT_CODE -ne 0 ]; then
        fail "step_${STEPS_DONE}"
    fi

    echo "[$STEPS_DONE/$STEPS_TOTAL] Done"

done < <(grep -v '^[[:space:]]*#' "$CONF" | grep -v '^[[:space:]]*$')

# all steps completed successfully
END_TIME=$(date +%s)
DURATION=$(( END_TIME - START_TIME ))

echo ""
echo "================================================"
echo " Pipeline complete"
echo " Steps:    $STEPS_DONE/$STEPS_TOTAL"
echo " Duration: ${DURATION}s"
echo " Finished: $(date)"
echo "================================================"
echo ""
echo "[INFO] Sending success alert + triggering resize..."

python3 "$EMIT" SUCCESS "$STEPS_DONE" "$STEPS_TOTAL" "$DURATION"
